In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression
import sys
sys.path.append("../")
from regression_markets.market.data import BatchData
from regression_markets.market.task import MaximumLikelihoodLinearRegression, BayesianLinearRegression


from regression_markets.market.policy import (
    KldCfModShapleyPolicy,
    KldContributionModShapleyPolicy,
    NllShapleyPolicy,
)
from regression_markets.market.mechanism import BatchMarket

In [16]:
noise_variance =  0.3
N=100000
q = np.random.normal(0, 1, size=N)
z0 = np.random.normal(0, 1, size=N)
x1 = z0 + np.random.normal(0, 0.3, size=N)
x2 = z0 + np.random.normal(0, 0.3, size=N) 
x2_r1 = x2 + np.random.normal(0, 0.3, size=N)  
x2_rK = x2 + np.random.normal(0, 0.3, size=N)  
ones = np.ones(N).reshape(-1, 1)


y = 0.5 * q + 0.9 * z0 + np.random.normal(0, noise_variance**0.5, size=N)

# lr = LinearRegression(fit_intercept=False)
all = np.vstack([
    q,
    x1,
    x2,
    x2_r1,
    #x2_rK,
]).T
task = MaximumLikelihoodLinearRegression(noise_variance=noise_variance)

# from sklearn.preprocessing import PolynomialFeatures
# poly = PolynomialFeatures(1, include_bias=False)
# X_poly = poly.fit_transform(all)
# lr.fit(X_poly, y)
# lr.coef_.round(2)

In [69]:

market_data = BatchData(ones, q.reshape(-1, 1), all[:, 1:], y.reshape(-1, 1), polynomial_degree=5)
market = BatchMarket(market_data, task, train_payment=1, observational=False
)

In [70]:
policy = NllShapleyPolicy(
            active_agents=market.market_data.active_agents,
            baseline_agents=market.market_data.baseline_agents,
            polynomial_degree=market.market_data.degree,
            regression_task=market.regression_task,
            observational=market.observational,
        )

In [71]:
output = market.run(NllShapleyPolicy)

In [72]:
output["train"]["contributions"]

array([-0.14745073, -3.15382471, 10.02754572, -5.00725236])

In [73]:
output["train"]["contributions"]

array([-0.14745073, -3.15382471, 10.02754572, -5.00725236])

In [74]:
output["train"]["contributions"]

array([-0.14745073, -3.15382471, 10.02754572, -5.00725236])